# Generated by Django 5.0.6 on 2026-07-06 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='direction',
            field=models.CharField(blank=True, choices=[('sent', 'Sent'), ('received', 'Received')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='network',
            field=models.CharField(choices=[('Ethereum', 'Ethereum'), ('Bitcoin', 'Bitcoin'), ('Polygon', 'Polygon'), ('BSC', 'BSC'), ('Solana', 'Solana'), ('Tron', 'Tron'), ('Zoro', 'Zoro')], default='Ethereum', max_length=30),
        ),
    ]
