# Generated by Django 5.0.6 on 2026-07-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(choices=[('USDT', 'USDT'), ('USDC', 'USDC'), ('BTC', 'BTC'), ('ETH', 'ETH'), ('BNB', 'BNB'), ('SOL', 'SOL'), ('ZOR', 'ZOR')], default='USDT', max_length=10),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='network',
            field=models.CharField(choices=[('Ethereum', 'Ethereum'), ('Bitcoin', 'Bitcoin'), ('Polygon', 'Polygon'), ('BSC', 'BSC'), ('Solana', 'Solana'), ('Tron', 'Tron'), ('Avalanche', 'Avalanche'), ('Zoro', 'Zoro')], default='Ethereum', max_length=30),
        ),
    ]
